movieterra/config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'api' do
    get '/recommendations', to: 'welcome#recommendations'
    post '/tickets', to: 'welcome#tickets'
  end

  root to: 'welcome#index'

  resources :movies do
    get :search, on: :collection
  end

  resources :users
  resources :tickets
  resource :session

end

movieterra/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

movieterra/app/models/movie.rb
class Movie < ApplicationRecord
  require 'open-uri'

  has_many :tickets
  has_one :planetakino_movie, class_name: 'PlanetakinoMovie', primary_key: 'id', foreign_key: 'tmdb_fk_id'

  def self.fetch(tmdb_id)
    cassette = "#{(tmdb_id / 1000) * 1000}/#{tmdb_id}"
    VCR.use_cassette(cassette) do
      Tmdb::Movie.detail(tmdb_id, language: 'ru')
    end
  rescue => error
    if error.to_s.last(20) == 'allowed limit of 40.'
      sleep 1.second
      retry
    end
  end

  def self.recommendation(*tmdb_ids)
    command = "cd /home/movieterra/env && . /home/movieterra/env/bin/activate && python3 planetakino_recommender.py -l #{tmdb_ids.join(' ')}"
    puts command
    `#{command}`.lines.last.tr('[]', '').split(',').to_a.map(&:to_i) rescue []
  end

  def self.screening
    Rails.cache.fetch('movies', expires_in: 12.hours) do
      xml = Nokogiri::XML(open('https://planetakino.ua/api/movies'))

      xml.search('movie').map do |movie|
        {
          id: movie.at('id').text.to_i,
          poster_url: movie.at('mainPosterUrl').text,
          title: movie.at('name').text,
          description: movie.at('description').text,
          length: movie.at('length').text,
          country: movie.at('country').text,
          genre: movie.at('genre').text,
          trailer: movie.at('youtube-id').text,
          url: movie.at('movieLink').text
        }
      end
    end
  end
end

movieterra/app/models/planetakino_movie.rb
class PlanetakinoMovie < ApplicationRecord
  belongs_to :movie, class_name: 'Movie', foreign_key: 'tmdb_fk_id'
end

movieterra/app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  #belongs_to :movie
  belongs_to :movie, primary_key: 'tmdb_id', class_name: 'Movie'

  validates :movie_id, uniqueness: { scope: :user }

  def movie_title
    Movie.fetch(movie_id).title
  end

  def poster_url
    poster_path = Movie.fetch(movie_id).poster_path
    poster_path.present? ? "https://image.tmdb.org/t/p/w300/#{poster_path}" : nil
  end
end

movieterra/app/models/user.rb
class User < ApplicationRecord
  has_many :tickets

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :update }
end

movieterra/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :auth
  helper_method :current_user

  def auth    
    session[:user_id] = User.create.id if session[:user_id].nil?
  end

  def current_user
    @current_user ||= User.find session[:user_id]
  rescue
    session[:user_id] = User.create.id
    retry
  end
end

movieterra/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def search
    movies = Tmdb::Search.movie(params[:title], language: 'ru').results.map do |movie|
      {
        id: movie.id,
        title: movie.title,
        year: movie.release_date
      }
    end

    render json: movies
  end
end

movieterra/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    reset_session
    redirect_to :root
  end
end

movieterra/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def create
    ActiveRecord::Base.transaction do
      @ticket = current_user.tickets.create(ticket_params)

      respond_to do |format|
        if @ticket.save
          format.html { redirect_to :root, notice: 'Ticket was successfully created.' }
          format.json { render :show, status: :created, location: @ticket }
        else
          format.html { render :new }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    @ticket = current_user.tickets.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to :root, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def ticket_params
      params.require(:ticket).permit(:movie_id)
    end
end

movieterra/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    current_user.update user_params
    redirect_to :root
  end


  private
    def user_params
      params.require(:user).permit(:email)
    end
end

movieterra/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :auth!, only: [:recommendations, :tickets]

  def index
    @user = current_user
    if current_user.tickets.present?
      #recommendations = PlanetakinoMovie.where(planetakino_id: Movie.recommendation(@user.tickets.pluck(:movie_id))).pluck(:planetakino_id)
      recommendations = Movie.recommendation(@user.tickets.pluck(:movie_id))
      @recommendation = Movie.screening.select { |x| recommendations.include? x[:id] }
    end
  end

  def recommendations
    @user = User.find(params[:user_id])
    recommendations = Movie.recommendation(@user.tickets.pluck(:movie_id))
    @recommendation = Movie.screening.select { |x| recommendations.include? x[:id] }
    render json: {
      movies: @recommendation.pluck(:id)
    }
  end

  def tickets
    user = User.find_or_create_by(id: params[:user_id])
    user.tickets.create(tmdb_id: params[:movie_id]) if params[:movie_id].present?
    render json: {
      movies: user.tickets.pluck(:tmdb_id)
    }
  end

  private

  def auth!
    head :forbidden if params[:access_key] != 'FCRpHzn8PugrkdWEHStNQDZh'
  end
end

movieterra/app/helpers/application_helper.rb
module ApplicationHelper
end

movieterra/app/helpers/sessions_helper.rb
module SessionsHelper
end

movieterra/app/helpers/tickets_helper.rb
module TicketsHelper
end

movieterra/app/helpers/users_helper.rb
module UsersHelper
end

movieterra/app/helpers/welcome_helper.rb
module WelcomeHelper
end

movieterra/app/views/layouts/application.html.slim
doctype html
html
  head
    title Movies
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag '//fonts.googleapis.com/css?family=PT+Sans|PT+Sans+Caption:400,700|PT+Sans+Narrow'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    #root
      = yield

movieterra/app/views/tickets/_form.html.slim
= form_for @ticket do |f|
  - if @ticket.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
      ul
        - @ticket.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user
    = f.select :user_id, options_for_select(User.all.map { |s| [s.name, s.id] })
  .field
    = f.label :movie_id
    = f.number_field :movie_id
  .actions = f.submit

movieterra/app/views/tickets/edit.html.slim
h1 Editing ticket

== render 'form'

= link_to 'Show', @ticket
'  |
= link_to 'Back', tickets_path

movieterra/app/views/tickets/index.html.slim
h1 Listing tickets

table
  thead
    tr
      th User
      th Tmdb
      th
      th
      th

  tbody
    - @tickets.each do |ticket|
      tr
        td = ticket.user
        td = ticket.tmdb_id
        td = link_to 'Show', ticket
        td = link_to 'Edit', edit_ticket_path(ticket)
        td = link_to 'Destroy', ticket, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Ticket', new_ticket_path

movieterra/app/views/tickets/new.html.slim
h1 New ticket

== render 'form'

= link_to 'Back', tickets_path

movieterra/app/views/tickets/show.html.slim
p#notice = notice

p
  strong User:
  = @ticket.user
p
  strong Tmdb:
  = @ticket.tmdb_id

= link_to 'Edit', edit_ticket_path(@ticket)
'  |
= link_to 'Back', tickets_path

movieterra/app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

movieterra/app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'  |
= link_to 'Back', users_path

movieterra/app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

movieterra/app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

movieterra/app/views/users/show.html.slim
p#notice = notice

.user
  h1 = @user.name

  .section.tickets
    h2 Рекомендации

  .section.tickets
    h2 Посещённые

    .tickets-list
      - @user.tickets.each do |ticket|
        .ticket
          .title
            = ticket.movie
          .poster
            - if ticket.poster_url.present?
              = image_tag ticket.poster_url

    = form_with model: [@user, @user.tickets.build] do |f|
      .field
        = f.label :tmdb_id
        = f.number_field :tmdb_id

      .actions = f.submit

  = link_to 'Back', users_path

movieterra/app/views/welcome/index.html.slim
header
  .container
    .heading
      span.name Movieterra
      span  — подбор интересных фильмов в кинотеатре

    .search
      .form
        = text_field 'title', '', placeholder: 'Какие фильмы вы смотрели в последнее время?', autofocus: true

      - if @user.tickets.present?
        .tickets
          - @user.tickets.reverse.each do |ticket|
            = link_to ticket, method: :delete, class: 'ticket' do
              .poster
                - if ticket.poster_url.present?
                  = image_tag ticket.poster_url

              .title
                = ticket.movie_title


- if @user.email.present?
  .section.subscribe
    .container
      .subscribed
        .email = @user.email
        = link_to 'Сменить пользователя', session_path, method: :delete


- if @recommendation.present?
  .section.recommendation
    .container
      .recommend
        h2.heading Вот на что бы мы вам посоветовали сходить в данный момент

        .movies
          - @recommendation.each do |movie|
            = link_to movie[:url], class: 'movie' do
              .poster
                = image_tag movie[:poster_url]
              .box
                h3.title = movie[:title]
                / .country = movie[:country]
                .genre = movie[:genre]
                .length = movie[:length]
                .description = movie[:description]


.section.instructions
  .container
    h2.heading Как это работает
    ul
      li
        .fa.fa-film
        .heading Выберите несколько фильмов
        p Чем больше укажете фильмов — тем точнее рекомендация

      li
        .fa.fa-user
        .heading Получите персональную рекомендацию
        p Рекомендации учитывают жанр, актёрский и режиссёрский составы, и пару секретных ингредиентов

      li
        .fa.fa-envelope
        .heading Подпишитесь на уведомления о новых фильмах
        p Мы уведомим вас, как только в кинотеатрах появится что-то стоящее


footer
  .container
    p Movieterra, 2017

movieterra/app/views/welcome/index2.html.slim
header
  .container
    .heading
      span.name Movieterra
      span  — подбор интересных фильмов в кинотеатре

    .search
      .form
        = text_field 'title', '', placeholder: 'Какие фильмы вы смотрели в последнее время?', autofocus: true

      - if @user.tickets.present?
        .tickets
          - @user.tickets.reverse.each do |ticket|
            = link_to ticket, method: :delete, class: 'ticket' do
              .poster
                - if ticket.poster_url.present?
                  = image_tag ticket.poster_url

              .title
                = ticket.movie_title


- if @user.email.present?
  .section.subscribe
    .container
      .subscribed
        .email = @user.email
        = link_to 'Сменить пользователя', session_path, method: :delete

- elsif @recommendation.present?
  - if @user.email.nil?
    .section.subscribe
      .container
        h2.heading Получать регулярно подборку интересных фильмов

        .email
          = form_with model: @user do |f|
            = f.text_field :email, placeholder: 'Электронная почта'
            = button_tag 'Получать подборку'

- if @recommendation.present?
  .section.recommendation
    .container
      .recommend
        h2.heading Вот на что бы мы вам посоветовали сходить в данный момент

        .movies
          - @recommendation.each do |movie|
            = link_to movie[:url], class: 'movie' do
              .poster
                = image_tag movie[:poster_url]
              .box
                h3.title = movie[:title]
                / .country = movie[:country]
                .genre = movie[:genre]
                .length = movie[:length]
                .description = movie[:description]


.section.instructions
  .container
    h2.heading Как это работает
    ul
      li
        .fa.fa-film
        .heading Выберите несколько фильмов
        p Чем больше укажете фильмов — тем точнее рекомендация

      li
        .fa.fa-user
        .heading Получите персональную рекомендацию
        p Рекомендации учитывают жанр, актёрский и режиссёрский составы, и пару секретных ингредиентов

      li
        .fa.fa-envelope
        .heading Подпишитесь на уведомления о новых фильмах
        p Мы уведомим вас, как только в кинотеатрах появится что-то стоящее


footer
  .container
    p Movieterra, 2017